url: https://myhuntnet.github.io
baseurl: 

# Site settings
title: MyHuntNet
email: sumeet@myhuntnet.com
description: "Make families lives easier."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Team names, titles and social links
people:
- name: Raj Desikavinayagompillai
  pic: 2
  position: Ops Hacker
  social:
    - title: linkedin
      url: http://linkedin.com/in/dnraj
    - title: github
      url: http://github.com/dnraj
    - title: twitter
      url: https://twitter.com/dnraj_72
- name: Sumeet Rohatgi
  pic: 1
  position: Chief
  social:
    - title: linkedin
      url: http://linkedin.com/in/sumeetrohatgi
    - title: github
      url: http://github.com/srohatgi
    - title: twitter
      url: https://twitter.com/sum_rtg
- name: Sonal Banka
  pic: 3
  position: Product Maven
  social:
    - title: linkedin
      url: http://www.linkedin.com/pub/sonal-banka/8/bb6/7b6
    - title: google-plus
      url: https://plus.google.com/108186295130296056369/about


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Fremont, CA 94539

# Build settings
markdown: kramdown
permalink: pretty
